### ISSUE TITLE
Random appear io timeout error

### ISSUE THREAD

**Issue by Ackerr** [elastic/apm-agent-python#1010]
**Describe the bug**: 

Every once in a while，all project use `apm-agent-python` will report an error.
```
TransportException("Unable to reach APM Server: HTTPConnectionPool(host='host', port=80): Read timed out. (read timeout=5) (url: http://host:80/intake/v2/events)")
```
but `apm-server` is normal and dont found related error report。

**To Reproduce**

1. restart apm-server (i think this because apm-server is not graceful shutdown)
2. random appear

**Environment (please complete the following information)**
- OS: [e.g. Linux] Linux
- Python version: 3.8.7
- Framework and version [e.g. Django 2.1]: Django 3.1 
- APM Server version: 7.10.1
- Agent version:  5.10.0

**Additional context*

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    ELASTIC_APM_SERVER_URL="host:80"
    ELASTIC_APM_TRANSACTIONS_IGNORE_PATTERNS="'^OPTIONS '"
    ELASTIC_APM_CAPTURE_BODY="transactions"
    ELASTIC_APM_TRANSACTION_SAMPLE_RATE="0.2"
    ELASTIC_APM_DJANGO_TRANSACTION_NAME_FROM_ROUTE="True"

    ```
  </details>
- `pipfile`:
  <details>
    <summary>Click to expand</summary>

    ```
    celery = "==4.4.7"
    django = "==3.1.3"
    django-cors-headers = "==3.5.0"
    django-mysql = "==3.9.0"
    django-mysql-geventpool = "==0.2.5"
    django-oss-storage = "==1.1.1"
    djangorestframework = "==3.12.2"
    djangorestframework-dataclasses = "0.8"
    drf-nested-routers = "==0.92.1"
    drf-yasg = "==1.20.0"
    elastic-apm = "==5.10.0"
    gevent = "==20.6.2"
    greenlet = "==0.4.16"
    grpcio = "==1.34.0"
    grpcio-status = "==1.34.0"
    gunicorn = "==20.0.4"
    kombu = "==4.6.11"
    pyjwt = "==1.7.1"
    pymysql = "==0.10.1"
    redis = "==3.5.3"
    sentry-sdk = "==0.19.4"
    ```
  </details>

- `apm-server`:
  <details>
    <summary>Click to expand</summary>

    ```
    apm-server.yml:
      host: 0.0.0.0:8200
      max_event_size: 10485760
      rum:
        enabled: true
        allow_origins: ['*']
    queue.mem.events: 12287
    output.elasticsearch:
      worker: 3
      bulk_max_size: 4096
      hosts: ["elasticsearch:9200"]
    logging.level: error
    apm-server.ilm: 
      enabled: "auto"
    ```
  </details>

**Comment by basepi** [comment]
Are you seeing any crashing or data loss along with this error? I'm not sure that these error logs are something you need to necessarily worry about, especially if you're making them happen with an APM Server restart.

**Comment by Ackerr** [comment]
Only found “forbidden requests” error in apm-server. I think it’s not urgent, but sometimes multiple agents will report this error at the same time on sentry.

**Comment by Ackerr** [comment]
[More context](https://discuss.elastic.co/t/random-appear-io-timeout-error-unable-to-reach-apm-server-read-timed-out/261488/2)

**Comment by basepi** [comment]
If multiple agents are reporting this at the same time, it leads me to believe it may be a brief network issue. I think the error is warranted in this case.

**Comment by Ackerr** [comment]
I try add lifecycle in apm-server.yml. Now, Then `rollout restart` apm-server，no more errors report.

```
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5 && kill -s HUP 1" ]
```
Random appear the error，not sure if it's because apm-server `queue.mem.events` set too large .
