### ISSUE TITLE
APM HTTP request information missing 

### ISSUE THREAD

**Issue by AhmadMS1988** [elastic/apm-agent-python#1148]
**Describe the bug**: ...
The request information like url.path and other information like headers and cookies are not found like what we were having in older elastic-apm version.

![Screen Shot 2021-06-03 at 8 49 58 PM](https://user-images.githubusercontent.com/33055837/120817275-3f9e4e80-c55a-11eb-8283-a89ca6fb4198.png)

**Environment (please complete the following information)**
- OS: container: amazon linux 2, host bottlerocket 1.1.1
- Python version: 3.7.9
- Framework and version [e.g. Django 2.1]: Django 2.2.11, djangorestframework==3.10.3, requests==2.22.0, mod-wsgi==4.8.0
- APM Server version: 7.13.0, deployed with ECK 1.6.0
- Agent version: 6.1.3 and 6.2.1
- Kibana version: 7.13.0
- Elasticsearch version: 7.13.0

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    ELASTIC_APM = {
        'SERVER_URL': 'https://elastic-apm-http.elasticsearch:8200',
        'SECRET_TOKEN': '******',
        'SERVICE_NAME': 'my-service-name',
        'ENVIRONMENT': 'dev',
        'CAPTURE_BODY': 'all',
        'DEBUG': True, # Please not that DEBUG is true to match Django debug on the dev environment.
        'INSTRUMENT': True,
        'TRANSACTION_IGNORE_URLS': ['/metrics', '*/health_check'],
        'DJANGO_TRANSACTION_NAME_FROM_ROUTE': True,
        'VERIFY_SERVER_CERT': False
    }
    ```
  </details>
- `requirements.txt`:
  <details>
    <summary>Click to expand</summary>

    ```
    django==2.2.11
    mysqlclient==1.4.6
    djangorestframework==3.10.3
    requests==2.22.0
    pytz==2020.1
    django-slack==5.14.3
    SQLAlchemy==1.3.13
    marshmallow==3.3.0
    marshmallow-sqlalchemy==0.21.0
    boto3==1.17.86
    drf-nested-routers==0.91
    elastic-apm==5.10.1
    mod-wsgi==4.8.0
    django-prometheus==2.1.0
    elasticsearch-dsl==7.1.0
    requests-aws4auth==0.9
    ```
  </details>
- `apm-server.yml`:
  <details>
    <summary>Click to expand</summary>

    ```
    apiVersion: apm.k8s.elastic.co/v1
    kind: ApmServer
    metadata:
      name: elastic
      namespace: elasticsearch
    spec:
      version: 7.13.0
      count: 4
      config:
        logging.level: warning
        monitoring.enabled: true
        output.elasticsearch.workers: 1
        output.elasticsearch.bulk_max_size: 4096
        queue.mem.events: 8192
      elasticsearchRef:
        name: elastic
      kibanaRef:
        name: elastic
      podTemplate:
        metadata:
          labels:
            apm-name: elastic
            elastic-rule: apm
        spec:
          containers:
            - name: apm-server
              resources:
                requests:
                  memory: 1Gi
                  cpu: .25
                limits:
                  memory: 2Gi
                  cpu: .5
          affinity:
            podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: elastic-rule
                      operator: In
                      values:
                      - apm
                  topologyKey: "kubernetes.io/hostname"
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                    - es
    ```
  </details>
Please note that when I downgraded to elastic-apm==5.10.1 the request information are displayed again.
Is it a removed feature, or there is something extra needs to be configured for 6.2.1?
best regards
